CREATE TABLE notifications (
    id                         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id                    BIGINT NOT NULL,
    app                        VARCHAR(64) NOT NULL,
    user_uid                   VARCHAR(255) NOT NULL,
    object_type                VARCHAR(64) NOT NULL DEFAULT '',
    object_id                  VARCHAR(255) NOT NULL DEFAULT '',
    subject                    VARCHAR(1024) NOT NULL DEFAULT '',
    subject_rich               VARCHAR(1024) NOT NULL DEFAULT '',
    subject_rich_parameters    TEXT NOT NULL,
    message                    TEXT NOT NULL,
    message_rich               TEXT NOT NULL,
    message_rich_parameters    TEXT NOT NULL,
    link                       VARCHAR(1024) NOT NULL DEFAULT '',
    icon                       VARCHAR(1024) NOT NULL DEFAULT '',
    should_notify              TINYINT NOT NULL DEFAULT 1,
    created_at                 BIGINT NOT NULL,
    KEY idx_notifications_user_id (user_id, id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE activities (
    id                         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id                    BIGINT NOT NULL,
    actor_uid                  VARCHAR(255) NOT NULL DEFAULT '',
    app                        VARCHAR(64) NOT NULL,
    type                       VARCHAR(64) NOT NULL DEFAULT '',
    subject                    VARCHAR(1024) NOT NULL DEFAULT '',
    subject_rich               VARCHAR(1024) NOT NULL DEFAULT '',
    subject_rich_parameters    TEXT NOT NULL,
    message                    TEXT NOT NULL,
    object_type                VARCHAR(64) NOT NULL DEFAULT '',
    object_id                  BIGINT NOT NULL DEFAULT 0,
    object_name                VARCHAR(1024) NOT NULL DEFAULT '',
    link                       VARCHAR(1024) NOT NULL DEFAULT '',
    icon                       VARCHAR(1024) NOT NULL DEFAULT '',
    created_at                 BIGINT NOT NULL,
    KEY idx_activities_user_id (user_id, id),
    CONSTRAINT fk_activities_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
